require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'WatchList' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'react-native-uuid-generator', :path => '../node_modules/react-native-uuid-generator'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  target 'WatchListTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'WatchList-tvOS' do
  # Pods for WatchList-tvOS

  target 'WatchList-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
